version: 2
jobs:
  build:
    docker: ubuntu:18.04
    steps:
      - apt-get update
      - apt-get install -y python3 python3-pip git curl wget make xz-utils file sudo unzip
      - checkout
      - run: ./build.sh
workflows:
  version: 2
  build:
    jobs:
    - build