version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y python3 python3-pip git curl wget make xz-utils file sudo unzip
      - run: apt-get install -y mecab libmecab-dev mecab-ipadic-utf8
      - checkout
      - run: ./build.sh
workflows:
  version: 2
  build:
    jobs:
    - build